### PR TITLE
Tap actions take #3

### PR DESCRIPTION
**Pull request by devmil**
This Pull Request covers the introduction of configurable tap actions.
The Double-Tap action and the Three-Finger action can be set to any of these values:
- Nothing
- Show original Artwork (= default behavior for Double-Tap and currently built into Muzei)
- Next Artwork (sends the Next command to the ArtSource)
- View Artwork details (opens the provided view Intent from the ArtSource)

This pull request has been re-based to the latest changes

### CODE REVIEW

**Comment by devmil** [comment]
Hi,
has this pull request any chance to get merged?
Would be nice to get a feedback on this because otherwise I could stop following the master branch changes.

**Comment by jdrbc** [comment]
bump :)

**Comment by piotrek1543** [comment]
@ianhanniballake any update or to close?

**Comment by ianhanniballake** [comment]
Re-did this PR in the now merged in #553

**Pull request closed without merging**
